cwl-compute-service:
  default_host: slurm

webdav:
# WebDAV configuration for storing files. Remove this
# section to have attachments stored in the task database.
  url: http://webdav
  username: webdav
  password: vadbew

hosts:
  das5:
    # Configuration of a single job host, using Xenon
    path: ${HOME}
    script: cwl-runner
    # Schema defines what submission system the host uses.
    host: slurm://fs0.das5.cs.vu.nl
    # Method is either ssh or xenon.
    method: xenon
    # time in minutes: 1 day
    max_time: 1440
    password: javagat

xenon:
  adaptors:
    slurm:
      ignore-version: true