version: '2'
services:
  compute-service:
    build:
      context: cwl-compute-service-service
    ports:
      - "127.0.0.1:3596"
    links:
      - webdav
      - slurm
  webdav:
    build:
      context: cwl-compute-service-webdav
    ports:
      - "127.0.0.1:3597:80"
  slurm:
    build:
      context: cwl-compute-service-slurm
    ports:
      - "127.0.0.1:3598:22"
    links:
      - webdav
